"""adicionando campo concluido

Revision ID: 8890924a75bb
Revises: e951e38e710f
Create Date: 2021-03-05 23:34:10.472103

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8890924a75bb'
down_revision = 'e951e38e710f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tarefas', sa.Column('concluido', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tarefas', 'concluido')
    # ### end Alembic commands ###
